[book]
title = "La référence du langage Rust"
author = "The Rust Project Developers"

[output.html]
additional-css = ["../theme/reference.css"]
git-repository-url = "https://github.com/Jimskapt/rust-reference-fr/"
